spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/pp_3_1_2'
    username: ppuser
    password: pppass
  jpa:
    #show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    hidden-method:
      filter:
        enabled: true
server:
  port: '8088'

#настройка cors
allowed:
  origin: 'http://localhost:8088/'